name: Restore Full Codebase via Script

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  restore:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run restore script
        run: |
          chmod +x scripts/restore_from_text.sh
          scripts/restore_from_text.sh legacy_pro_v6.7_corrected.txt

      - name: Commit restored files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -B legacypro-full-restore
          git add .
          git commit -m "Restore full codebase from text file"
          git push --force origin legacypro-full-restore
